// Complete list of currencies supported by ExchangeRate-API
// Generated from API response, includes all 163 currencies

export const CURRENCIES = [
  // Major World Currencies
  { code: 'USD', name: 'US Dollar', symbol: '$', popular: true },
  { code: 'EUR', name: 'Euro', symbol: '€', popular: true },
  { code: 'GBP', name: 'British Pound', symbol: '£', popular: true },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', popular: true },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', popular: true },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr', popular: true },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', popular: true },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', popular: true },
  
  // Asia-Pacific
  { code: 'THB', name: 'Thai Baht', symbol: '฿', popular: true },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', popular: true },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', popular: true },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', popular: true },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', popular: true },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$' },
  { code: 'MOP', name: 'Macau Pataca', symbol: 'MOP$' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'रू' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ' },
  { code: 'TMT', name: 'Turkmenistan Manat', symbol: 'm' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'soʻm' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
  
  // Europe
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', popular: true },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'din' },
  { code: 'BAM', name: 'Bosnia Mark', symbol: 'KM' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼' },
  
  // Americas
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', popular: true },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', popular: true },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: 'G$' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$' },
  { code: 'TTD', name: 'Trinidad Dollar', symbol: 'TT$' },
  { code: 'BBD', name: 'Barbados Dollar', symbol: 'Bds$' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: 'CI$' },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: 'BD$' },
  
  // Middle East
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', popular: true },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', popular: true },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب' },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل' },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£S' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼' },
  
  // Africa
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', popular: true },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC' },
  { code: 'XAF', name: 'Central African CFA', symbol: 'FCFA' },
  { code: 'XOF', name: 'West African CFA', symbol: 'CFA' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$' },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le' },
  { code: 'SLL', name: 'Sierra Leonean Leone (old)', symbol: 'Le' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM' },
  { code: 'STN', name: 'São Tomé Príncipe Dobra', symbol: 'Db' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nkf' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh.So.' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar' },
  
  // Pacific
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', popular: true },
  { code: 'FJD', name: 'Fiji Dollar', symbol: 'FJ$' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣' },
  { code: 'KID', name: 'Kiribati Dollar', symbol: '$' },
  { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$' },
  
  // Other/Special
  { code: 'XDR', name: 'IMF Special Drawing Rights', symbol: 'SDR' },
  { code: 'XCG', name: 'Caribbean Gold', symbol: 'XCG' },
  { code: 'FOK', name: 'Faroese Króna', symbol: 'kr' },
  { code: 'GGP', name: 'Guernsey Pound', symbol: '£' },
  { code: 'IMP', name: 'Isle of Man Pound', symbol: '£' },
  { code: 'JEP', name: 'Jersey Pound', symbol: '£' },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£' },
];

export function getCurrencyByCode(code: string) {
  return CURRENCIES.find(c => c.code === code);
}

export function getPopularCurrencies() {
  return CURRENCIES.filter(c => c.popular);
}