/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiConfigSplatRouteImport } from './routes/api/config/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppSettingsIndexRouteImport } from './routes/_auth/app/settings/index'
import { Route as AuthAppAdvancedIndexRouteImport } from './routes/_auth/app/advanced/index'
import { Route as ApiConfigStaticSplatRouteImport } from './routes/api/config/static/$'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiConfigSplatRoute = ApiConfigSplatRouteImport.update({
  id: '/api/config/$',
  path: '/api/config/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppSettingsIndexRoute = AuthAppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppAdvancedIndexRoute = AuthAppAdvancedIndexRouteImport.update({
  id: '/app/advanced/',
  path: '/app/advanced/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiConfigStaticSplatRoute = ApiConfigStaticSplatRouteImport.update({
  id: '/api/config/static/$',
  path: '/api/config/static/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/config/$': typeof ApiConfigSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/api/config/static/$': typeof ApiConfigStaticSplatRoute
  '/app/advanced': typeof AuthAppAdvancedIndexRoute
  '/app/settings': typeof AuthAppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/config/$': typeof ApiConfigSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/api/config/static/$': typeof ApiConfigStaticSplatRoute
  '/app/advanced': typeof AuthAppAdvancedIndexRoute
  '/app/settings': typeof AuthAppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/config/$': typeof ApiConfigSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/api/config/static/$': typeof ApiConfigStaticSplatRoute
  '/_auth/app/advanced/': typeof AuthAppAdvancedIndexRoute
  '/_auth/app/settings/': typeof AuthAppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/api/config/$'
    | '/app'
    | '/api/config/static/$'
    | '/app/advanced'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/api/config/$'
    | '/app'
    | '/api/config/static/$'
    | '/app/advanced'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/api/auth/$'
    | '/api/config/$'
    | '/_auth/app/'
    | '/api/config/static/$'
    | '/_auth/app/advanced/'
    | '/_auth/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConfigSplatRoute: typeof ApiConfigSplatRoute
  ApiConfigStaticSplatRoute: typeof ApiConfigStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/config/$': {
      id: '/api/config/$'
      path: '/api/config/$'
      fullPath: '/api/config/$'
      preLoaderRoute: typeof ApiConfigSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/settings/': {
      id: '/_auth/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/advanced/': {
      id: '/_auth/app/advanced/'
      path: '/app/advanced'
      fullPath: '/app/advanced'
      preLoaderRoute: typeof AuthAppAdvancedIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/config/static/$': {
      id: '/api/config/static/$'
      path: '/api/config/static/$'
      fullPath: '/api/config/static/$'
      preLoaderRoute: typeof ApiConfigStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppAdvancedIndexRoute: typeof AuthAppAdvancedIndexRoute
  AuthAppSettingsIndexRoute: typeof AuthAppSettingsIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppAdvancedIndexRoute: AuthAppAdvancedIndexRoute,
  AuthAppSettingsIndexRoute: AuthAppSettingsIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConfigSplatRoute: ApiConfigSplatRoute,
  ApiConfigStaticSplatRoute: ApiConfigStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
