/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsFeaturesReportsRouteImport } from './routes/docs/features/reports'
import { Route as DocsFeaturesEntriesRouteImport } from './routes/docs/features/entries'
import { Route as DocsFeaturesConnectionsRouteImport } from './routes/docs/features/connections'
import { Route as ApiDataSplatRouteImport } from './routes/api/data/$'
import { Route as ApiDataStaticSplatRouteImport } from './routes/api/data/static/$'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFeaturesReportsRoute = DocsFeaturesReportsRouteImport.update({
  id: '/features/reports',
  path: '/features/reports',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFeaturesEntriesRoute = DocsFeaturesEntriesRouteImport.update({
  id: '/features/entries',
  path: '/features/entries',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFeaturesConnectionsRoute = DocsFeaturesConnectionsRouteImport.update({
  id: '/features/connections',
  path: '/features/connections',
  getParentRoute: () => DocsRoute,
} as any)
const ApiDataSplatRoute = ApiDataSplatRouteImport.update({
  id: '/api/data/$',
  path: '/api/data/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataStaticSplatRoute = ApiDataStaticSplatRouteImport.update({
  id: '/api/data/static/$',
  path: '/api/data/static/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/': typeof DocsIndexRoute
  '/api/data/$': typeof ApiDataSplatRoute
  '/docs/features/connections': typeof DocsFeaturesConnectionsRoute
  '/docs/features/entries': typeof DocsFeaturesEntriesRoute
  '/docs/features/reports': typeof DocsFeaturesReportsRoute
  '/api/data/static/$': typeof ApiDataStaticSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs': typeof DocsIndexRoute
  '/api/data/$': typeof ApiDataSplatRoute
  '/docs/features/connections': typeof DocsFeaturesConnectionsRoute
  '/docs/features/entries': typeof DocsFeaturesEntriesRoute
  '/docs/features/reports': typeof DocsFeaturesReportsRoute
  '/api/data/static/$': typeof ApiDataStaticSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/': typeof DocsIndexRoute
  '/api/data/$': typeof ApiDataSplatRoute
  '/docs/features/connections': typeof DocsFeaturesConnectionsRoute
  '/docs/features/entries': typeof DocsFeaturesEntriesRoute
  '/docs/features/reports': typeof DocsFeaturesReportsRoute
  '/api/data/static/$': typeof ApiDataStaticSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/'
    | '/api/data/$'
    | '/docs/features/connections'
    | '/docs/features/entries'
    | '/docs/features/reports'
    | '/api/data/static/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/getting-started'
    | '/docs'
    | '/api/data/$'
    | '/docs/features/connections'
    | '/docs/features/entries'
    | '/docs/features/reports'
    | '/api/data/static/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/getting-started'
    | '/docs/'
    | '/api/data/$'
    | '/docs/features/connections'
    | '/docs/features/entries'
    | '/docs/features/reports'
    | '/api/data/static/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  ApiDataSplatRoute: typeof ApiDataSplatRoute
  ApiDataStaticSplatRoute: typeof ApiDataStaticSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/features/reports': {
      id: '/docs/features/reports'
      path: '/features/reports'
      fullPath: '/docs/features/reports'
      preLoaderRoute: typeof DocsFeaturesReportsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/features/entries': {
      id: '/docs/features/entries'
      path: '/features/entries'
      fullPath: '/docs/features/entries'
      preLoaderRoute: typeof DocsFeaturesEntriesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/features/connections': {
      id: '/docs/features/connections'
      path: '/features/connections'
      fullPath: '/docs/features/connections'
      preLoaderRoute: typeof DocsFeaturesConnectionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/data/$': {
      id: '/api/data/$'
      path: '/api/data/$'
      fullPath: '/api/data/$'
      preLoaderRoute: typeof ApiDataSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/static/$': {
      id: '/api/data/static/$'
      path: '/api/data/static/$'
      fullPath: '/api/data/static/$'
      preLoaderRoute: typeof ApiDataStaticSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsFeaturesConnectionsRoute: typeof DocsFeaturesConnectionsRoute
  DocsFeaturesEntriesRoute: typeof DocsFeaturesEntriesRoute
  DocsFeaturesReportsRoute: typeof DocsFeaturesReportsRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsFeaturesConnectionsRoute: DocsFeaturesConnectionsRoute,
  DocsFeaturesEntriesRoute: DocsFeaturesEntriesRoute,
  DocsFeaturesReportsRoute: DocsFeaturesReportsRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  ApiDataSplatRoute: ApiDataSplatRoute,
  ApiDataStaticSplatRoute: ApiDataStaticSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
