import type { Category } from "@repo/shared-lib"
import {
	BabyIcon,
	BatteryPlusIcon,
	BriefcaseIcon,
	BriefcaseMedicalIcon,
	CarIcon,
	DropletsIcon,
	DumbbellIcon,
	ForkKnifeIcon,
	GiftIcon,
	GraduationCapIcon,
	HandCoinsIcon,
	HomeIcon,
	HotelIcon,
	HousePlugIcon,
	type LucideIcon,
	MartiniIcon,
	PawPrintIcon,
	PercentIcon,
	PiggyBankIcon,
	PlaneIcon,
	RepeatIcon,
	ShieldIcon,
	ShoppingBagIcon,
	ShoppingCartIcon,
	SparklesIcon,
	SquirrelIcon,
	ZapIcon,
} from "lucide-react"

export const categoryIcons: Record<Category, LucideIcon> = {
	Food: ForkKnifeIcon,
	Groceries: ShoppingCartIcon,
	Transportation: CarIcon,
	Shopping: ShoppingBagIcon,
	Bills: ZapIcon,
	Insurance: ShieldIcon,
	Entertainment: MartiniIcon,
	Health: BriefcaseMedicalIcon,
	"Personal Care": DropletsIcon,
	Household: HousePlugIcon,
	Beauty: SparklesIcon,
	Rent: HomeIcon,
	Accommodation: HotelIcon,
	Flights: PlaneIcon,
	Subscriptions: RepeatIcon,
	Fitness: DumbbellIcon,
	Education: GraduationCapIcon,
	Therapy: BatteryPlusIcon,
	Taxes: PercentIcon,
	Pets: PawPrintIcon,
	Children: BabyIcon,
	Investment: PiggyBankIcon,
	Salary: HandCoinsIcon,
	Business: BriefcaseIcon,
	Gift: GiftIcon,
	Other: SquirrelIcon,
} as const

export const getCategoryIcon = (category: string) => {
	return categoryIcons[category as Category] ?? SquirrelIcon
}
