export const currencies = [
	"USD",
	"EUR",
	"AED",
	"AFN",
	"ALL",
	"AMD",
	"ANG",
	"AOA",
	"ARS",
	"AUD",
	"AWG",
	"AZN",
	"BAM",
	"BBD",
	"BDT",
	"BGN",
	"BHD",
	"BIF",
	"BMD",
	"BND",
	"BOB",
	"BRL",
	"BSD",
	"BTN",
	"BWP",
	"BYN",
	"BZD",
	"CAD",
	"CDF",
	"CHF",
	"CLP",
	"CNY",
	"COP",
	"CRC",
	"CUP",
	"CVE",
	"CZK",
	"DJF",
	"DKK",
	"DOP",
	"DZD",
	"EGP",
	"ERN",
	"ETB",
	"FJD",
	"FKP",
	"FOK",
	"GBP",
	"GEL",
	"GGP",
	"GHS",
	"GIP",
	"GMD",
	"GNF",
	"GTQ",
	"GYD",
	"HKD",
	"HNL",
	"HRK",
	"HTG",
	"HUF",
	"IDR",
	"ILS",
	"IMP",
	"INR",
	"IQD",
	"IRR",
	"ISK",
	"JEP",
	"JMD",
	"JOD",
	"JPY",
	"KES",
	"KGS",
	"KHR",
	"KID",
	"KMF",
	"KRW",
	"KWD",
	"KYD",
	"KZT",
	"LAK",
	"LBP",
	"LKR",
	"LRD",
	"LSL",
	"LYD",
	"MAD",
	"MDL",
	"MGA",
	"MKD",
	"MMK",
	"MNT",
	"MOP",
	"MRU",
	"MUR",
	"MVR",
	"MWK",
	"MXN",
	"MYR",
	"MZN",
	"NAD",
	"NGN",
	"NIO",
	"NOK",
	"NPR",
	"NZD",
	"OMR",
	"PAB",
	"PEN",
	"PGK",
	"PHP",
	"PKR",
	"PLN",
	"PYG",
	"QAR",
	"RON",
	"RSD",
	"RUB",
	"RWF",
	"SAR",
	"SBD",
	"SCR",
	"SDG",
	"SEK",
	"SGD",
	"SHP",
	"SLE",
	"SLL",
	"SOS",
	"SRD",
	"SSP",
	"STN",
	"SYP",
	"SZL",
	"THB",
	"TJS",
	"TMT",
	"TND",
	"TOP",
	"TRY",
	"TTD",
	"TVD",
	"TWD",
	"TZS",
	"UAH",
	"UGX",
	"UYU",
	"UZS",
	"VES",
	"VND",
	"VUV",
	"WST",
	"XAF",
	"XCD",
	"XCG",
	"XDR",
	"XOF",
	"XPF",
	"YER",
	"ZAR",
	"ZMW",
	"ZWL",
	"CLF",
	"CNH",
] as const

export type Currency = (typeof currencies)[number]

export type CurrencyData = { symbol: string; name: string }

export const currencyData: Record<Currency, CurrencyData> = {
	USD: { symbol: "$", name: "United States Dollar" },
	AED: { symbol: "د.إ", name: "United Arab Emirates Dirham" },
	AFN: { symbol: "؋", name: "Afghan Afghani" },
	ALL: { symbol: "Lek", name: "Albanian Lek" },
	AMD: { symbol: "֏", name: "Armenian Dram" },
	ANG: { symbol: "ƒ", name: "Netherlands Antillean Guilder" },
	AOA: { symbol: "Kz", name: "Angolan Kwanza" },
	ARS: { symbol: "$", name: "Argentine Peso" },
	AUD: { symbol: "$", name: "Australian Dollar" },
	AWG: { symbol: "Afl", name: "Aruban Florin" },
	AZN: { symbol: "₼", name: "Azerbaijani Manat" },
	BAM: { symbol: "KM", name: "Bosnia and Herzegovina Convertible Mark" },
	BBD: { symbol: "$", name: "Barbadian Dollar" },
	BDT: { symbol: "৳", name: "Bangladeshi Taka" },
	BGN: { symbol: "лв", name: "Bulgarian Lev" },
	BHD: { symbol: "د.ب", name: "Bahraini Dinar" },
	BIF: { symbol: "FBu", name: "Burundian Franc" },
	BMD: { symbol: "$", name: "Bermudian Dollar" },
	BND: { symbol: "$", name: "Brunei Dollar" },
	BOB: { symbol: "Bs.", name: "Bolivian Boliviano" },
	BRL: { symbol: "R$", name: "Brazilian Real" },
	BSD: { symbol: "$", name: "Bahamian Dollar" },
	BTN: { symbol: "Nu.", name: "Bhutanese Ngultrum" },
	BWP: { symbol: "P", name: "Botswanan Pula" },
	BYN: { symbol: "Br", name: "Belarusian Ruble" },
	BZD: { symbol: "BZ$", name: "Belize Dollar" },
	CAD: { symbol: "$", name: "Canadian Dollar" },
	CDF: { symbol: "FC", name: "Congolese Franc" },
	CHF: { symbol: "CHF", name: "Swiss Franc" },
	CLP: { symbol: "$", name: "Chilean Peso" },
	CNY: { symbol: "¥", name: "Chinese Yuan" },
	COP: { symbol: "$", name: "Colombian Peso" },
	CRC: { symbol: "₡", name: "Costa Rican Colón" },
	CUP: { symbol: "$", name: "Cuban Peso" },
	CVE: { symbol: "Esc", name: "Cape Verdean Escudo" },
	CZK: { symbol: "Kč", name: "Czech Koruna" },
	DJF: { symbol: "Fdj", name: "Djiboutian Franc" },
	DKK: { symbol: "kr", name: "Danish Krone" },
	DOP: { symbol: "RD$", name: "Dominican Peso" },
	DZD: { symbol: "د.ج", name: "Algerian Dinar" },
	EGP: { symbol: "E£", name: "Egyptian Pound" },
	ERN: { symbol: "Nfk", name: "Eritrean Nakfa" },
	ETB: { symbol: "Br", name: "Ethiopian Birr" },
	EUR: { symbol: "€", name: "Euro" },
	FJD: { symbol: "$", name: "Fijian Dollar" },
	FKP: { symbol: "£", name: "Falkland Islands Pound" },
	FOK: { symbol: "kr", name: "Faroese Króna" },
	GBP: { symbol: "£", name: "British Pound" },
	GEL: { symbol: "₾", name: "Georgian Lari" },
	GGP: { symbol: "£", name: "Guernsey Pound" },
	GHS: { symbol: "₵", name: "Ghanaian Cedi" },
	GIP: { symbol: "£", name: "Gibraltar Pound" },
	GMD: { symbol: "D", name: "Gambian Dalasi" },
	GNF: { symbol: "FG", name: "Guinean Franc" },
	GTQ: { symbol: "Q", name: "Guatemalan Quetzal" },
	GYD: { symbol: "$", name: "Guyanese Dollar" },
	HKD: { symbol: "$", name: "Hong Kong Dollar" },
	HNL: { symbol: "L", name: "Honduran Lempira" },
	HRK: { symbol: "kn", name: "Croatian Kuna" },
	HTG: { symbol: "G", name: "Haitian Gourde" },
	HUF: { symbol: "Ft", name: "Hungarian Forint" },
	IDR: { symbol: "Rp", name: "Indonesian Rupiah" },
	ILS: { symbol: "₪", name: "Israeli New Shekel" },
	IMP: { symbol: "£", name: "Isle of Man Pound" },
	INR: { symbol: "₹", name: "Indian Rupee" },
	IQD: { symbol: "ع.د", name: "Iraqi Dinar" },
	IRR: { symbol: "﷼", name: "Iranian Rial" },
	ISK: { symbol: "kr", name: "Icelandic Króna" },
	JEP: { symbol: "£", name: "Jersey Pound" },
	JMD: { symbol: "J$", name: "Jamaican Dollar" },
	JOD: { symbol: "د.ا", name: "Jordanian Dinar" },
	JPY: { symbol: "¥", name: "Japanese Yen" },
	KES: { symbol: "KSh", name: "Kenyan Shilling" },
	KGS: { symbol: "с", name: "Kyrgyzstani Som" },
	KHR: { symbol: "៛", name: "Cambodian Riel" },
	KID: { symbol: "$", name: "Kiribati Dollar" },
	KMF: { symbol: "CF", name: "Comorian Franc" },
	KRW: { symbol: "₩", name: "South Korean Won" },
	KWD: { symbol: "د.ك", name: "Kuwaiti Dinar" },
	KYD: { symbol: "CI$", name: "Cayman Islands Dollar" },
	KZT: { symbol: "₸", name: "Kazakhstani Tenge" },
	LAK: { symbol: "₭", name: "Lao Kip" },
	LBP: { symbol: "ل.ل", name: "Lebanese Pound" },
	LKR: { symbol: "Rs", name: "Sri Lankan Rupee" },
	LRD: { symbol: "$", name: "Liberian Dollar" },
	LSL: { symbol: "L", name: "Lesotho Loti" },
	LYD: { symbol: "ل.د", name: "Libyan Dinar" },
	MAD: { symbol: "د.م.", name: "Moroccan Dirham" },
	MDL: { symbol: "L", name: "Moldovan Leu" },
	MGA: { symbol: "Ar", name: "Malagasy Ariary" },
	MKD: { symbol: "ден", name: "Macedonian Denar" },
	MMK: { symbol: "K", name: "Burmese Kyat" },
	MNT: { symbol: "₮", name: "Mongolian Tögrög" },
	MOP: { symbol: "MOP$", name: "Macanese Pataca" },
	MRU: { symbol: "UM", name: "Mauritanian Ouguiya" },
	MUR: { symbol: "₨", name: "Mauritian Rupee" },
	MVR: { symbol: "Rf", name: "Maldivian Rufiyaa" },
	MWK: { symbol: "MK", name: "Malawian Kwacha" },
	MXN: { symbol: "$", name: "Mexican Peso" },
	MYR: { symbol: "RM", name: "Malaysian Ringgit" },
	MZN: { symbol: "MT", name: "Mozambican Metical" },
	NAD: { symbol: "$", name: "Namibian Dollar" },
	NGN: { symbol: "₦", name: "Nigerian Naira" },
	NIO: { symbol: "C$", name: "Nicaraguan Córdoba" },
	NOK: { symbol: "kr", name: "Norwegian Krone" },
	NPR: { symbol: "₨", name: "Nepalese Rupee" },
	NZD: { symbol: "$", name: "New Zealand Dollar" },
	OMR: { symbol: "ر.ع.", name: "Omani Rial" },
	PAB: { symbol: "B/.", name: "Panamanian Balboa" },
	PEN: { symbol: "S/", name: "Peruvian Sol" },
	PGK: { symbol: "K", name: "Papua New Guinean Kina" },
	PHP: { symbol: "₱", name: "Philippine Peso" },
	PKR: { symbol: "₨", name: "Pakistani Rupee" },
	PLN: { symbol: "zł", name: "Polish Zloty" },
	PYG: { symbol: "₲", name: "Paraguayan Guaraní" },
	QAR: { symbol: "ر.ق", name: "Qatari Riyal" },
	RON: { symbol: "lei", name: "Romanian Leu" },
	RSD: { symbol: "дин.", name: "Serbian Dinar" },
	RUB: { symbol: "₽", name: "Russian Ruble" },
	RWF: { symbol: "FRw", name: "Rwandan Franc" },
	SAR: { symbol: "ر.س", name: "Saudi Riyal" },
	SBD: { symbol: "$", name: "Solomon Islands Dollar" },
	SCR: { symbol: "₨", name: "Seychellois Rupee" },
	SDG: { symbol: "ج.س", name: "Sudanese Pound" },
	SEK: { symbol: "kr", name: "Swedish Krona" },
	SGD: { symbol: "$", name: "Singapore Dollar" },
	SHP: { symbol: "£", name: "Saint Helena Pound" },
	SLE: { symbol: "Le", name: "Sierra Leonean Leone" },
	SLL: { symbol: "Le", name: "Sierra Leonean Leone" },
	SOS: { symbol: "Sh", name: "Somali Shilling" },
	SRD: { symbol: "$", name: "Surinamese Dollar" },
	SSP: { symbol: "£", name: "South Sudanese Pound" },
	STN: { symbol: "Db", name: "São Tomé and Príncipe Dobra" },
	SYP: { symbol: "ل.س", name: "Syrian Pound" },
	SZL: { symbol: "E", name: "Eswatini Lilangeni" },
	THB: { symbol: "฿", name: "Thai Baht" },
	TJS: { symbol: "SM", name: "Tajikistani Somoni" },
	TMT: { symbol: "m", name: "Turkmenistani Manat" },
	TND: { symbol: "د.ت", name: "Tunisian Dinar" },
	TOP: { symbol: "T$", name: "Tongan Paʻanga" },
	TRY: { symbol: "₺", name: "Turkish Lira" },
	TTD: { symbol: "TT$", name: "Trinidad and Tobago Dollar" },
	TVD: { symbol: "$", name: "Tuvaluan Dollar" },
	TWD: { symbol: "NT$", name: "New Taiwan Dollar" },
	TZS: { symbol: "TSh", name: "Tanzanian Shilling" },
	UAH: { symbol: "₴", name: "Ukrainian Hryvnia" },
	UGX: { symbol: "USh", name: "Ugandan Shilling" },
	UYU: { symbol: "$U", name: "Uruguayan Peso" },
	UZS: { symbol: "so'm", name: "Uzbekistani So'm" },
	VES: { symbol: "Bs.", name: "Venezuelan Bolívar" },
	VND: { symbol: "₫", name: "Vietnamese Đồng" },
	VUV: { symbol: "Vt", name: "Vanuatu Vatu" },
	WST: { symbol: "T", name: "Samoan Tala" },
	XAF: { symbol: "FCFA", name: "Central African CFA Franc" },
	XCD: { symbol: "$", name: "East Caribbean Dollar" },
	XCG: { symbol: "¤", name: "Generic Currency" },
	XDR: { symbol: "SDR", name: "Special Drawing Rights" },
	XOF: { symbol: "CFA", name: "West African CFA Franc" },
	XPF: { symbol: "₣", name: "CFP Franc" },
	YER: { symbol: "﷼", name: "Yemeni Rial" },
	ZAR: { symbol: "R", name: "South African Rand" },
	ZMW: { symbol: "ZK", name: "Zambian Kwacha" },
	ZWL: { symbol: "$", name: "Zimbabwean Dollar" },
	CLF: { symbol: "UF", name: "Chilean Unit of Account (UF)" },
	CNH: { symbol: "¥", name: "Chinese Yuan (Offshore)" },
} as const

export function getCurrencySymbol(code: Currency): string {
	return currencyData[code].symbol
}

export function getCurrencyName(code: Currency): string {
	return currencyData[code].name
}
